root: true
owner: CERN
start_year: 2014
substring: This file is part of
template: |-
  {comment_start} This file is part of the CERN Indico plugins.
  {comment_middle} Copyright (C) {dates} {owner}
  {comment_middle}
  {comment_middle} The CERN Indico plugins are free software; you can redistribute
  {comment_middle} them and/or modify them under the terms of the MIT License; see
  {comment_middle} the LICENSE file for more details.
  {comment_end}
